[package]
name = "kistaverk_core"
version = "0.1.0"
edition = "2024"

[lib]
name = "kistaverk_core"  # Optionnel mais recommand√© pour forcer le nom du .so
crate-type = ["cdylib"]

[dependencies]
jni = "0.21"           # The bridge
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"